apiVersion: v2
name: geoserver-wfs-yahalom
type: application
version: 1.0.4
appVersion: 1.0.4
description: Chart for yahalom WFS geoserver in openshift
dependencies:
  - name: nginx
    version: 2.1.6
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
    condition: enabled
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
