global:
  cloudProvider: {}
  environment: ''
  db: {}
  tracing: {}
  metrics: {}
  storage: {}
  geoserver: {}
  serviceUrls: {}

mclabels:
  #environment: development
  component: backend
  partOf: yahalom-serving
  owner: 3d
  gisDomain: 3d
  prometheus:
    enabled: true
    port: 9117
  longScraping: true

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'

tracing:
  enabled: false
metrics:
  enabled: false
  prometheus:
    scrape: false
    ## Note: this is set to 12345 because this is the port the metrics goes to in the geoserver itself as set in the docker image
    port: 12345

### Useful for umbrella deployments in cases which no need geoserver serving ###
enabled: true
imagePullPolicy: Always

image:
  geoserverRepository: geoserver-os
  geoserverTag: "latest"
  sidecarRepository: yahalom-geoserver-side-car
  sidecarTag: "latest"

updateInterval: 10000

replicaCount: 1

nameOverride:
fullnameOverride: layers-wfs-geoserver

initialMemory: "128M"
maxMemory: "756M"

storage:
  fs:
    internalPvc:
      name: ""
      mountPath: "/data_dir"
      geoserverDataDirSubPath: ""
geoserver:
  secrets:
    createSecret: true
  auth:
    password: ""
    username: ""
  workspace: ""
  dataStore: ""
serviceUrls:
  geoserverUrl: ""
  geoserverApiUrl: ""
  catalogManager: ""

readiness:
  path: "/geoserver" # change it according to workspace name changing

db:
  host: ""
  name: ""
  port: 5432

rootCerts:
  enabled: false
  secretName: secret-name
  mountPath: '/tmp/root-certs'

pgSslAuth:
  enabled: false
  secretName: secret-name
  mountPath: '/tmp/certs-postgres'

# Define this for extra GeoServer environment variables
extraGeoserverEnv: |
  - name: COMMUNITY_EXTENSIONS
    value: "cog-plugin"
  - name: JAVA_OPTS
    value: '-DALLOW_ENV_PARAMETRIZATION=true'
  - name: PROXY_BASE_URL
    value: /geoserver 
#  - name: KEY_2
#    value: "VALUE_2"

extraSidecarEnv: ""
#  - name: KEY_1
#    value: "VALUE_1"
#  - name: KEY_2
#    value: "VALUE_2"

labels: {}
annotations: {}

podAnnotations: {}

resources:
  enabled: false
  limits:
    cpu: 2
    memory: 4500Mi
  requests:
    cpu: 2
    memory: 4000Mi

sidecarResources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  ## GeoServer service type
  type: ClusterIP
  # clusterIP: ""
  # externalIPs: ""
  port: 80

  # nodePort:

  labels: ""
  annotations: ""
  # loadBalancerIP:

  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

route:
  enabled: false
  tls: false
  path: /geoserver

sideCar:
  env:
    logLevel: "info"
    logPretty: "false"
    pollingIntervalMs: 3000
    # ssl:
    #   CA_DIR: /opt/certs/ca/
    #   KEY_DIR: /opt/certs/key/
    #   CERT_DIR: /opt/certs/cert/
    #   CA_FILE_LOCATION: /opt/certs/ca/ca.pem
    #   KEY_FILE_LOCATION: /opt/certs/key/key.pem
    #   CERT_FILE_LOCATION: /opt/certs/cert/cert.pem

    featureTypesBlackLists:
      tableNamesRegex:
        - '.*_history$'
        - '.*_valid$'
      tableNameStrings:
        - migrations
        - layer_objects
        - sync_state

nginx:
  enabled: true
  replicaCount: 1
  fullnameOverride: 
  nameOverride: layers-wfs-geoserver-nginx
  image:
    repository: common/nginx
  mclabels:
    gisDomain: 3d
    partOf: yahalom-serving
    owner: 3d
  extensions:
    server:
      enabled: true
      fileName: geoserver-server.conf
    location:
      enabled: true
      fileName: geoserver-location.conf
  port: 8080
  internalServicePort: 80
  targetPort: 8080
  nodePort: 30001
  clientMaxBodySize: 50m

  opentelemetry:
    serviceName: layers-wfs-geoserver-nginx
    exporterHost: infra-otel.infra-services
    exporterPort: 4317
    samplerMethod: "AlwaysOff"
    ratio: 10

  backend:
    host: layers-wfs-geoserver-service
    port: 80
    
  prometheusExporter:
    # -- Enable or disable the Prometheus exporter sidecar
    enabled: true
    image:
      # -- Docker image name for the Prometheus exporter
      repository: common/nginx/nginx-prometheus-exporter
      # -- Docker image tag for the Prometheus exporter
      tag: latest
      # -- Image pull policy for the Prometheus exporter
      pullPolicy: IfNotPresent
    resources:
      # -- Enable or disable resource limits and requests
      enabled: true
      value:
        limits:
          # -- CPU limit for the main container
          cpu: 100m
          # -- Memory limit for the main container
          memory: 128Mi
        requests:
          # -- CPU request for the main container
          cpu: 100m
          # -- Memory request for the main container
          memory: 128Mi    

  authorization:
    enabled: true
    domain: 'raster'
    url: http://opa-service.infra-services/v1/data/http/authz/decision

  extraVolumes:
  - name: nginx-config
    configMap:
      name: '{{ .Release.Name }}-nginx-configmap'

  extraVolumeMounts:
  - name: nginx-config
    mountPath: "/etc/nginx/conf.d/extensions/geoserver-location.conf"
    subPath: geoserver-location.conf
  - name: nginx-config
    mountPath: "/etc/nginx/conf.d/extensions/geoserver-server.conf"
    subPath: geoserver-server.conf

  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  route:
    enabled: true
    routesMapping:
    - host:
      path: /api/raster/v1
    rewriteTarget: "/geoserver"
    timeout:
      enabled: false # defaults to 30s by openshift
      duration: 60s # supported units (us, ms, s, m, h, d)
    tls:
      enabled: true
      useCerts: false
      certificate: ''
      key: ''
      caCertificate: ''

  ingress:
    enabled: false
    ingressClassName: ''
    ingressMapping:
    - host: 'localhost'
      path: /api/raster/v1
      pathType: Prefix
    tls:
      enabled: true
      useExternal: ''
